### ISSUE TITLE
Problem downloading NC files

### ISSUE THREAD

**Issue by Alerovere** [pyReef-model/RADWave#6]
Hello, I am trying to run RadWave in the South Atlantic, but I get the error pasted below. 
If I go to the link mentioned in the error, I can download the .nc file, so I am not sure what's going on here. Any hint?
All works with no issues with the example datasets.

Here is my code
wa = rwave.waveAnalysis(altimeterURL='../dataset/IMOSURLs.txt', bbox=[-66.0, -63.0,-46.0,-42.0], 
                  stime=[1985,1,1], etime=[2021,1,1])

<img width="1017" alt="Screenshot 2023-06-30 at 10 38 04" src="https://github.com/pyReef-model/RADWave/assets/16379400/5d78fc6d-add8-4752-830d-38cebcc38365">

**Comment by tristan-salles** [comment]
Maybe there was a potential error on the IMOS server, I did try it this morning using the binder link below:
https://mybinder.org/v2/gh/tristan-salles/CoastProc-notebooks/master?urlpath=tree/waveclimate.ipynb

and it worked fine.

**Comment by Alerovere** [comment]
Still no luck, it all works with your example file, so my RADWAVE installation should be OK. Maybe, if you have time, you can try this file on your end and see if you can spot anything unusual?
Here's my code

wa = rwave.waveAnalysis(altimeterURL='../dataset/IMOS_Camarones.txt', bbox=[-64.9, -60.9,-46.9,-43.3], 
                 stime=[2000,1,1], etime=[2023,1,1])

#Spatial: From Lat/Lon -46.9, -64.9 to Lat/Lon -43.3, -60.9
#Temporal: 2000-Jan-01-00:00-UTC to 2
[IMOS_Camarones.txt](https://github.com/pyReef-model/RADWave/files/11925249/IMOS_Camarones.txt)

**Comment by tristan-salles** [comment]
It seems that it works when changing all the start of the urls in your .txt file from:

`https://imos-data.s3-ap-southeast-2.amazonaws.com`
to
`https://thredds.aodn.org.au/thredds/dodsC`

But you might also need to change your lon/lat coordinates in the `bbox` to reflect the netcdf files you have selected  **[295.1, 299.1, -46.9, -43.3]**

[IMOS_Camarones.txt](https://github.com/pyReef-model/RADWave/files/11925550/IMOS_Camarones.txt)
![Untitled](https://github.com/pyReef-model/RADWave/assets/7201912/b95300e2-322b-4f69-aa5b-f262a8235a51)

**Comment by Alerovere** [comment]
Tristan, thanks so much for looking into this. It works on my end now, substituting the link.
Sorry for the coords, I was putting them into a -180/180 grid, not 0-360
